using System.Collections.Generic;
using UnityEngine;

public static class StringsToBold
{
	//public static string ReplaceWithBold(string text)
	//{
	//	string newText = text;

	//	foreach (var boldedString in BoldedStrings)
	//	{
	//		newText = newText.Replace(boldedString, $"<b>{boldedString}</b>");
	//	}

	//	text = newText;
	//	return text;
	//}

	//private static readonly HashSet<string> BoldedStrings = new HashSet<string>()
	//{
	//	"Match Plot",
	//	"Toad Card",
	//	"Reward:",
	//	"Activity",
	//	"Break Event",
	//	"Trinket",
	//	"Kill",
	//	"Toad Card's Power",
	//	"Toad Card's Health",
		
	//	"0/0 Weapon",
	//	"0/1 Weapon",
	//	"1/0 Weapon",
	//	"1/1 Weapon",

	//	"2/0 Weapon",
	//	"2/1 Weapon",
	//	"0/2 Weapon",
	//	"1/2 Weapon",
	//	"2/2 Weapon",

	//	"3/0 Weapon",
	//	"3/1 Weapon",
	//	"3/2 Weapon",
	//	"0/3 Weapon",
	//	"1/3 Weapon",
	//	"2/3 Weapon",
	//	"3/3 Weapon",

	//	"4/0 Weapon",
	//	"4/1 Weapon",
	//	"4/2 Weapon",
	//	"4/3 Weapon",
	//	"0/4 Weapon",
	//	"1/4 Weapon",
	//	"2/4 Weapon",
	//	"3/4 Weapon",
	//	"4/4 Weapon",

	//	"5/0 Weapon",
	//	"5/1 Weapon",
	//	"5/2 Weapon",
	//	"5/3 Weapon",
	//	"5/4 Weapon",
	//	"0/5 Weapon",
	//	"1/5 Weapon",
	//	"2/5 Weapon",
	//	"3/5 Weapon",
	//	"4/5 Weapon",
	//	"5/5 Weapon",

	//	"6/0 Weapon",
	//	"6/1 Weapon",
	//	"6/2 Weapon",
	//	"6/3 Weapon",
	//	"6/4 Weapon",
	//	"6/5 Weapon",
	//	"0/6 Weapon",
	//	"1/6 Weapon",
	//	"2/6 Weapon",
	//	"3/6 Weapon",
	//	"4/6 Weapon",
	//	"5/6 Weapon",
	//	"6/6 Weapon",

	//	"7/0 Weapon",
	//	"7/1 Weapon",
	//	"7/2 Weapon",
	//	"7/3 Weapon",
	//	"7/4 Weapon",
	//	"7/5 Weapon",
	//	"7/6 Weapon",
	//	"0/7 Weapon",
	//	"1/7 Weapon",
	//	"2/7 Weapon",
	//	"3/7 Weapon",
	//	"4/7 Weapon",
	//	"5/7 Weapon",
	//	"6/7 Weapon",
	//	"7/7 Weapon",
	//	"Weapon",
	//	"Weapon's",

	//	"+1 Armor",
	//	"+2 Armor",
	//	"+3 Armor",
	//	"+4 Armor",
	//	"+5 Armor",
	//	"+6 Armor",
	//	"+7 Armor",
	//	"+8 Armor",
	//	"+9 Armor",
	//	"+10 Armor",
	//	"+11 Armor",
	//	"+12 Armor",
	//	"+13 Armor",
	//	"+14 Armor",
	//	"+15 Armor",
	//	"-1 Armor",
	//	"-2 Armor",
	//	"-3 Armor",
	//	"-4 Armor",
	//	"-5 Armor",
	//	"-6 Armor",
	//	"-7 Armor",
	//	"-8 Armor",
	//	"-9 Armor",
	//	"-10 Armor",
	//	"-11 Armor",
	//	"-12 Armor",
	//	"-13 Armor",
	//	"-14 Armor",
	//	"-15 Armor",
	//	"1 Armor",
	//	"2 Armor",
	//	"3 Armor",
	//	"4 Armor",
	//	"5 Armor",
	//	"6 Armor",
	//	"7 Armor",
	//	"8 Armor",
	//	"9 Armor",
	//	"10 Armor",
	//	"11 Armor",
	//	"12 Armor",
	//	"13 Armor",
	//	"14 Armor",
	//	"15 Armor",
	//	"Armor",

	//	"+1 Power",
	//	"+2 Power", 
	//	"+3 Power", 
	//	"+4 Power", 
	//	"+5 Power", 
	//	"+6 Power", 
	//	"+7 Power", 
	//	"+8 Power", 
	//	"+9 Power", 
	//	"+10 Power",
	//	"+11 Power",
	//	"+12 Power",
	//	"+13 Power",
	//	"+14 Power",
	//	"+15 Power",
	//	"-1 Power", 
	//	"-2 Power", 
	//	"-3 Power", 
	//	"-4 Power", 
	//	"-5 Power", 
	//	"-6 Power", 
	//	"-7 Power", 
	//	"-8 Power", 
	//	"-9 Power", 
	//	"-10 Power",
	//	"-11 Power",
	//	"-12 Power",
	//	"-13 Power",
	//	"-14 Power",
	//	"-15 Power",
	//	"1 Power",
	//	"2 Power",
	//	"3 Power",
	//	"4 Power",
	//	"5 Power",
	//	"6 Power",
	//	"7 Power",
	//	"8 Power",
	//	"9 Power",
	//	"10 Power",
	//	"11 Power",
	//	"12 Power",
	//	"13 Power",
	//	"14 Power",
	//	"15 Power",
	//	"Power",

	//	"+1 Health",
	//	"+2 Health",
	//	"+3 Health",
	//	"+4 Health",
	//	"+5 Health",
	//	"+6 Health",
	//	"+7 Health",
	//	"+8 Health",
	//	"+9 Health",
	//	"+10 Health",
	//	"+11 Health",
	//	"+12 Health",
	//	"+13 Health",
	//	"+14 Health",
	//	"+15 Health",
	//	"-1 Health",
	//	"-2 Health",
	//	"-3 Health",
	//	"-4 Health",
	//	"-5 Health",
	//	"-6 Health",
	//	"-7 Health",
	//	"-8 Health",
	//	"-9 Health",
	//	"-10 Health",
	//	"-11 Health",
	//	"-12 Health",
	//	"-13 Health",
	//	"-14 Health",
	//	"-15 Health",
	//	"1 Health",
	//	"2 Health",
	//	"3 Health",
	//	"4 Health",
	//	"5 Health",
	//	"6 Health",
	//	"7 Health",
	//	"8 Health",
	//	"9 Health",
	//	"10 Health",
	//	"11 Health",
	//	"12 Health",
	//	"13 Health",
	//	"14 Health",
	//	"15 Health",
	//	"Health",

	//	"1 Damage",
	//	"2 Damage",
	//	"3 Damage",
	//	"4 Damage",
	//	"5 Damage",
	//	"6 Damage",
	//	"7 Damage",
	//	"8 Damage",
	//	"9 Damage",
	//	"10 Damage",
	//	"11 Damage",
	//	"12 Damage",
	//	"13 Damage",
	//	"14 Damage",
	//	"15 Damage",
	//	"Damage",

	//	"1 Grub",
	//	"2 Grub",
	//	"3 Grub",
	//	"4 Grub",
	//	"5 Grub",
	//	"6 Grub",
	//	"7 Grub",
	//	"8 Grub",
	//	"9 Grub",
	//	"10 Grub",
	//	"11 Grub",
	//	"12 Grub",
	//	"13 Grub",
	//	"14 Grub",
	//	"15 Grub",
	//	"Grub",

	//	"Discards 1 Card",
	//	"Discards 2 Cards",
	//	"Discards 3 Cards",
	//	"Discards 4 Cards",
	//	"Discards 5 Cards",
	//	"Discards 6 Cards",
	//	"Discards 7 Cards",
	//	"Discards 8 Cards",
	//	"Discards 9 Cards",
	//	"Discards 10 Cards",
	//	"Discard",

	//	"Draw 1 Card",
	//	"Draw 2 Cards",
	//	"Draw 3 Cards",
	//	"Draw 4 Cards",
	//	"Draw 5 Cards",
	//	"Draw 6 Cards",
	//	"Draw 7 Cards",
	//	"Draw 8 Cards",
	//	"Draw 9 Cards",
	//	"Draw 10 Cards",

	//	"1 Card",
	//	"2 Cards",
	//	"3 Cards",
	//	"4 Cards",
	//	"5 Cards",
	//	"6 Cards",
	//	"7 Cards",
	//	"8 Cards",
	//	"9 Cards",
	//	"10 Cards",
	//	"11 Cards",
	//	"12 Cards",
	//	"13 Cards",
	//	"14 Cards",
	//	"15 Cards",
	//};
}
